export default function PrivacyPage() {
  return (
    <div style={{ padding: '80px var(--spacing-xl)', maxWidth: '900px', margin: '0 auto' }}>
      <h1 className="display-xl" style={{ marginBottom: 'var(--spacing-lg)', letterSpacing: '-1px' }}>Privacy Policy</h1>
      <p className="body-lg" style={{ marginBottom: 'var(--spacing-3xl)', color: 'var(--body)' }}>
        Your privacy is critically important to us. This document outlines how the Rules Engine handles data during simulations and production use.
      </p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--spacing-xl)' }}>
        <div className="card-content">
          <h2 className="body-lg" style={{ fontWeight: 900, marginBottom: 'var(--spacing-md)' }}>1. Data Collection & Processing</h2>
          <p className="body-md" style={{ marginBottom: 'var(--spacing-md)', lineHeight: 1.6 }}>
            The Rules Engine operates entirely on anonymous behavioral streams. We process event types (such as <code>view_item</code>, <code>add_to_cart</code>, <code>checkout_started</code>) and their corresponding timestamps.
          </p>
          <ul style={{ paddingLeft: '24px', display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: 'var(--spacing-md)' }}>
            <li className="body-md"><strong>No PII:</strong> We do not require, collect, or store Personally Identifiable Information (like names, emails, or IP addresses) in our rule evaluation pipeline.</li>
            <li className="body-md"><strong>In-Memory Evaluation:</strong> Event streams sent to the <code>/api/evaluate</code> endpoint are processed in memory and are discarded immediately after the HTTP response is dispatched.</li>
          </ul>
        </div>

        <div className="card-feature-sage">
          <h2 className="body-lg" style={{ fontWeight: 900, marginBottom: 'var(--spacing-md)' }}>2. Storage & Persistence</h2>
          <p className="body-md" style={{ marginBottom: 'var(--spacing-md)', lineHeight: 1.6 }}>
            Our MongoDB database is used strictly for storing the <strong>configuration rules</strong> (the logical thresholds and nudges). It does not store user session data, tracking cookies, or historical event logs.
          </p>
          <p className="body-md" style={{ lineHeight: 1.6 }}>
            For the Simulator tool, all events are kept locally in your browser's React state. If you refresh the page, your simulation history is permanently erased.
          </p>
        </div>

        <div className="card-content">
          <h2 className="body-lg" style={{ fontWeight: 900, marginBottom: 'var(--spacing-md)' }}>3. Third-Party Sharing</h2>
          <p className="body-md" style={{ lineHeight: 1.6 }}>
            Because we do not store session data, we have nothing to share. We do not sell, rent, or trade any analytical data to advertising partners or third-party trackers. The insights generated by the engine are returned exclusively to the client making the API request.
          </p>
        </div>

        <div className="card-content">
          <h2 className="body-lg" style={{ fontWeight: 900, marginBottom: 'var(--spacing-md)' }}>4. Security & Rate Limiting</h2>
          <p className="body-md" style={{ lineHeight: 1.6 }}>
            To protect our infrastructure from abuse, the API utilizes a strict rate limiter (capped at 50 requests per 15-minute window per IP). The IP addresses used for rate limiting are temporarily hashed in memory and are never persisted to a database.
          </p>
        </div>
      </div>
    </div>
  );
}
